#!/bin/bash
#
# Copy Twitter Bootstrap files into place.
# I know there's probably a cleaner way to do this, but I don't feel
# like spending the time for something I never expect to change.
#

pushd "`dirname $0`/.." > /dev/null

BOOTSTRAP_DIR="vendor/twbs/bootstrap/dist"
BUNDLE_DIR="web/bundles/bootstrap"

mkdir -p "${BUNDLE_DIR}"

mkdir -p "${BUNDLE_DIR}/fonts"
mkdir -p "${BUNDLE_DIR}/css"
mkdir -p "${BUNDLE_DIR}/js"

cp -v ${BOOTSTRAP_DIR}/fonts/* "${BUNDLE_DIR}/fonts/"
cp -v ${BOOTSTRAP_DIR}/css/* "${BUNDLE_DIR}/css/"
cp -v ${BOOTSTRAP_DIR}/js/* "${BUNDLE_DIR}/js/"

popd > /dev/null

