// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "CatPooServer.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ;

class CatPooServerHandler : virtual public CatPooServerIf {
 public:
  CatPooServerHandler() {
    // Your initialization goes here
  }

  void setServoSpeed(const int32_t index, const int32_t speed) {
    // Your implementation goes here
    printf("setServoSpeed\n");
  }

  void activateServo(const int32_t index, const int32_t direction) {
    // Your implementation goes here
    printf("activateServo\n");
  }

  void takePicture(const int32_t index, const std::string& filename) {
    // Your implementation goes here
    printf("takePicture\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<CatPooServerHandler> handler(new CatPooServerHandler());
  shared_ptr<TProcessor> processor(new CatPooServerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

