parameters:
#    timmd909_cat_poo.example.class: timmd909\CatPooBundle\Example

services:
#    timmd909_cat_poo.example:
#        class: %timmd909_cat_poo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
