#!/bin/bash
#
# This should be run by crontab 
#

pushd "`dirname $0`" > /dev/null

echo "Starting up button watcher"
screen -dm -S watch-button ./watch-button

for TTS in tts/*; do 
	echo "Running $TTS"
	./$TTS
done


popd > /dev/null 
