#!/bin/bash

GPIO="$1"
MODE="$2"

if [ "$GPIO" = "" }; then
	echo "Usage: $0 <gpio#> [<mode>]"
	exit 1
fi

if [ "$MODE" = "" ]; then
	MODE="out"
fi

echo $GPIO > "/sys/class/gpio/export"
echo $MODE > "/sys/class/gpio/gpio$GPIO/direction"
