#!/bin/bash 
#============================================================================
# Name        : thrift-gen
# Author      : Tim Doerzbacher <tim@tim-doerzbacher.com>
# Version     : nunyabidness
# Copyright   : See LICENSE
# Description : CATPOO Thrift Server
# ============================================================================

# -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- 

pushd "`dirname \"$0\"`/.." > /dev/null 

THRIFT_DIR="$PWD/include/thrift"

function prepare_output_dir()
{
	rm -rf $1/*.cpp $1/*.h 
	mkdir -p "$1"
}

popd > /dev/null 

# -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- 

pushd "$THRIFT_DIR" > /dev/null

for X in *.thrift; do 	
	echo -en "\033[34;1mCreating \033[33;1m$X\033[34;1m..."
	
	# -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- 
	OUTPUT_DIR="../../vision/thrift"
	prepare_output_dir "$OUTPUT_DIR" 
	thrift -r --strict --gen cpp -out "$OUTPUT_DIR" "$X"
	
	# -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- 
	#OUTPUT_DIR="../../motion/thrift"
	#prepare_output_dir "$OUTPUT_DIR"
	#thrift -r --gen erl -out "$OUTPUT_DIR" "$X"
	OUTPUT_DIR="../../motion/thrift"
	prepare_output_dir "$OUTPUT_DIR"
	thrift -r --strict --gen cpp -out "$OUTPUT_DIR" "$X"
	
	# -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- 
	echo -e " \033[32;1mdone\033[0m"
done 

popd > /dev/null

# -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- 
