#!/bin/bash

function extract_ip_address()
{
	DEVICE=$1
	ifconfig $DEVICE | grep -o 'addr\:[0-9]*.[0-9]*.[0-9]*.[0-9]*' | sed 's/\./ dot  /g' | cut -d\: -f2
}

function speak()
{
	echo "$1" | festival --tts
}

function check_device()
{
	DEVICE="$1"
	TYPE="$2"
	
	SPEECH=""
	
	if [ "`ifconfig -a | grep $DEVICE | wc -l `" -lt 1 ]; then
		SPEECH="$SPEECH $TYPE device not found"
	else 
		SPEECH="$SPEECH Found device $TYPE"

		if [ `ifconfig  $DEVICE | grep inet | wc -l ` -lt 1 ]; then
			SPEECH="$SPEECH but it is not available"
		else
			SPEECH="$SPEECH and has connected. Eye pee address is `extract_ip_address $DEVICE`"
		fi	
		
	fi 
	
	speak "$SPEECH"
	
}

check_device "eth0"   "Ether net zero"

check_device "wlan0"  "Wire less zero"
check_device "wlan1"  "Wire less one"
